### ISSUE TITLE
Remove .DS_Store & add requirements.txt

### ISSUE THREAD

**Issue by imfht** [neverlovelynn/chrome_headless_xss#1]
Hi，多谢你的分享，这是一个很不错的项目，属于国内使用 HeadlessChrome 进行 web2.0安全检测为数不多的开源代码之一。
我想这个代码还可以更专业一点，可以去掉.DS_Store文件并加上requirements.txt文件 ;-D

**Comment by neverlovelynn** [comment]
Hi,已经将.DS_Store去掉，并且加上了requirements.txt文件。另外通过将payload所在位置的nodeValue进行渲染判断了一下是否经过编码。但是因为异步的问题感觉代码逻辑稍微简陋了一点，有在使用的话希望可以多测试一下，如果出现bug可以告诉我。
