### ISSUE TITLE
关于chrome_headless_xss和url_location

### ISSUE THREAD

**Issue by d4wner** [neverlovelynn/chrome_headless_xss#2]
想请教git主两个问题，期待能得到回复哈~
1.chrome_headless_xss中好像是对alert的事件进行hook的，有没有考虑过改成console之类的事件，因为不少黑名单是对alert进行了检测的。
2.url_location是对url跳转进行检测的么？个人觉得是否不会比普通requests返回结果更高效？因为这个跟也不涉及dom之类的问题。

**Comment by neverlovelynn** [comment]
第一个问题如果你仔细看了代码的话
是弹窗事件都进行了hook，其次这只是判断xss的一种渠道，我还通过了自定义标签是否能解析到dom，payload是否经过编码输出来判断是否存在xss。

第二个问题
url跳转不仅仅是后端可以做，前端js一样可以做，使用chromeheadless的主要原因是解决前端跳转检测不到的情况。以及有时候可以找到一些iframe注入的问题。

d4wner <notifications@github.com>于2018年11月11日 周日16:26写道：

**Comment by d4wner** [comment]
Get，另外本地实测：
```
result_json["params"]["url"] 
```
调试信息如下：
```
{u'params': {u'message': u'123', u'type': u'alert'}, u'method': u'Page.javascriptDialogOpening'}
```
可能没有url这个key，导致第250行那里没判断过来，抛出错误。
我不知道是我用错了，还是这里就是个bug，所以还是给楼主提一下：
```
客户端：
    chrome_headless_drive = ChromeHeadLess(url="http://192.168.xxx.xxx/xss.php?test=<img src=x onerror=alert(123)>",
                                           ip="127.0.0.1", port="9222",
                                           cookie="",
                                           post="",
                                           auth="",
                                           payload='''test_test''',
                                           check_message="123")
```
web端xss.php：
```
<?php
echo $_GET['test'];
?>

**Comment by neverlovelynn** [comment]
我自己本地测试的时候没有出现你说的情况。url最好使用'''url'''来支持换行
payload应该要填 你自己的payload 如 你这里应该是 "<img src=x onerror=alert(123)>"
另外 附上我自己常用的几个payload:
'<marquee loop=1 width=0  onfinish=javascript:a=alert;a(123)>
'<webscan></webscan>
'<svg/onload=[1].find(alert)>
另外你用的chrome_headless的版本是啥？我感觉你这个异常可能是版本不一致导致的。
欢迎多沟通

**Comment by neverlovelynn** [comment]
另外可以的话 可以把你的联系方式告诉我。通过issue沟通效率太低了。

**Comment by d4wner** [comment]
我那边yum装有点问题，所以百度盘下的deb包装的，好像chrome版本是v60吧，链接如下：
 ```
http://www.cnblogs.com/tdcqma/p/7374856.html
```
另外，我其他两个level倒是测试过了，这里没改而已，嘿嘿。
